(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
(* http://mathematica.stackexchange.com/questions/29321/what-are-the-best-practices-most-common-idiomatic-ways-to-report-errors-in-m#6563886 *)


(* ::Input::Initialization:: *)
BeginPackage["ErrorChecking`"];


(* ::Input::Initialization:: *)
setConsistencyChecks::usage="Completes definition of a function f by f[input___]:=(Message[f::argerror,input];$Failed). The function has a Listable attribute";


(* ::Input::Initialization:: *)
Begin["`Private`"];


(* ::Input::Initialization:: *)
Clear[setConsistencyChecks];
Attributes[setConsistencyChecks]={Listable};
setConsistencyChecks[function_Symbol,Optional[additionalMessage_String,""]]:=
Module[{},
function::argerror="Invalid input: `1`.\n `2`";
function[input___]:=(Message[function::argerror,{input},additionalMessage];$Failed)];

setConsistencyChecks[___]:=$Failed


(* ::Input::Initialization:: *)
End[];

EndPackage[];



